exports.data = [
  {
    "name" : "Romneya Apartment Lease1",
    "userId" : null,
    "landlordId" : null,
    "occupants" : [
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": true},
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": false},
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": false},
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": false},
    ],
    "beginDate" : "2015-04-23",
    "term" : "fixed",
    "expireDate" : "2016-04-23",
    "basicLeaseTerms" : {
        "aptNumber" : "101C",
        "address" : "810 W Romneya Dr",
        "monthlyRent" : 1200,
        "securityDeposit" : 1000,
        "remoteDeposit" : 0,
        "garageOrStorage" : 100,
        "lateRentCharge" : 75,
        "dishonoredCheck" : 50,
        "hotWater" : true,
        "coldWater" : true,
        "gas" : true,
        "electrical" : false,
        "gardening" : false,
        "trash" : true,
        "parkingAssignments" : ["1", "7"]
    },
    "ackPossessionOfPremises" : false,
    "ackRent" : true,
    "payableTo" : "Romneya Management Team",
    "ackLateChargeBadCheck" : true,
    "ackSecurityDeposit" : true,
    "ackUtilities" : true,
    "ackOccupancy" : true,
    "ackCoResidents": true,
    "ackAcceptanceOfPremises": true,
    "ackKeys" : true,
    "ackUseOfPremises" : true,
    "ackWaterFurniture" : true,
    "ackDamage" : true,
    "ackSmoke" : true,
    "ackCO2" : true,
    "ackLandlordEntry" : true,
    "ackVehiclesAndParking" : true,
    "ackSubletting" : true,
    "ackLiablility" : true,
    "ackPretermination" : true,
    "ackRelocation" : true,
    "ackDefault" : true,
    "ackAttorneysFee" : true,
    "ackRenewal" : true,
    "ackTerminationMonthToMonth" : true,
    "ackChangeInTerms" : true,
    "ackWaiver" : true,
    "ackReleaseOfInformation" : true,
    "ackMegansLaw" : true,
    "ackProp65" : true,
    "ackCommunityRules" : true,
    "ackPetPolicy" : true,
    "ackSatelliteDishAndAntenna" : true,
    "ackPestControl" : true,
    "ackMoldAndMildew" : true,
    "ackTenantInsurance" : true,
    "signatures" : ["signature1", "signature2", "signature3"],
    "pets" : ["cat1", "cat2"],
    "parking" : ["parking1"],
    "createDate" : "2012-04-23",
    "signDate" : "2012-04-23",
    "status": "complete",
  },
  {
    "name" : "Romneya Apartment Lease2",
    "userId" : null,
    "landlordId" : null,
    "occupants" : [
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": true},
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": false},
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": false},
      {"firstName": "maria", "middleName": "juana", "lastName": "mandana", "adult": false},
    ],
    "beginDate" : "2016-04-23",
    "term" : "fixed",
    "expireDate" : "2017-04-23",
    "basicLeaseTerms" : {
        "aptNumber" : "101C",
        "address" : "810 W Romneya Dr",
        "monthlyRent" : 1200,
        "securityDeposit" : 1000,
        "remoteDeposit" : 0,
        "garageOrStorage" : 100,
        "lateRentCharge" : 75,
        "dishonoredCheck" : 50,
        "hotWater" : true,
        "coldWater" : true,
        "gas" : true,
        "electrical" : false,
        "gardening" : false,
        "trash" : true,
        "parkingAssignments" : ["1", "7"]
    },
    "ackPossessionOfPremises" : false,
    "ackRent" : true,
    "payableTo" : "Romneya Management Team",
    "ackLateChargeBadCheck" : true,
    "ackSecurityDeposit" : true,
    "ackUtilities" : true,
    "ackOccupancy" : true,
    "ackCoResidents": true,
    "ackAcceptanceOfPremises": true,
    "ackKeys" : true,
    "ackUseOfPremises" : true,
    "ackWaterFurniture" : true,
    "ackDamage" : true,
    "ackSmoke" : true,
    "ackCO2" : true,
    "ackLandlordEntry" : true,
    "ackVehiclesAndParking" : true,
    "ackSubletting" : true,
    "ackLiablility" : true,
    "ackPretermination" : true,
    "ackRelocation" : true,
    "ackDefault" : true,
    "ackAttorneysFee" : true,
    "ackRenewal" : true,
    "ackTerminationMonthToMonth" : true,
    "ackChangeInTerms" : true,
    "ackWaiver" : true,
    "ackReleaseOfInformation" : true,
    "ackMegansLaw" : true,
    "ackProp65" : true,
    "ackCommunityRules" : true,
    "ackPetPolicy" : true,
    "ackSatelliteDishAndAntenna" : true,
    "ackPestControl" : true,
    "ackMoldAndMildew" : true,
    "ackTenantInsurance" : true,
    "signatures" : ["signature1", "signature2", "signature3"],
    "pets" : ["cat1", "cat2"],
    "parking" : ["parking1"],
    "createDate" : "2012-04-23",
    "signDate" : "2012-04-23",
    "status": "pending",
  }
]
